on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Write to console
        run: echo Hello world from Marti!
   
